config/routes.rb
Rails.application.routes.draw do
  resources :miniaturas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "miniaturas#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/miniatura.rb
class Miniatura < ApplicationRecord
  scope :por_marca_carro, ->(marca_carro) { where(marca_carro: marca_carro) if marca_carro.present? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/miniaturas_controller.rb
class MiniaturasController < ApplicationController
  before_action :set_miniatura, only: %i[ show edit update destroy ]

  # GET /miniaturas or /miniaturas.json
  def index
    sort_column = params[:sort] || "marca_carro"
    sort_direction = params[:direction] || "asc"
    @miniaturas = Miniatura.order("#{sort_column} #{sort_direction}")

    @miniaturas = Miniatura.por_marca_carro(params[:marca_carro])
    @marcas_carro = Miniatura.distinct.pluck(:marca_carro).compact.sort
  end

  # GET /miniaturas/1 or /miniaturas/1.json
  def show
  end

  # GET /miniaturas/new
  def new
    @miniatura = Miniatura.new
  end

  # GET /miniaturas/1/edit
  def edit
  end

  # POST /miniaturas or /miniaturas.json
  def create
    @miniatura = Miniatura.new(miniatura_params)

    respond_to do |format|
      if @miniatura.save
        format.html { redirect_to @miniatura, notice: "Miniatura was successfully created." }
        format.json { render :show, status: :created, location: @miniatura }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @miniatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /miniaturas/1 or /miniaturas/1.json
  def update
    respond_to do |format|
      if @miniatura.update(miniatura_params)
        format.html { redirect_to @miniatura, notice: "Miniatura was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @miniatura }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @miniatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /miniaturas/1 or /miniaturas/1.json
  def destroy
    @miniatura.destroy!

    respond_to do |format|
      format.html { redirect_to miniaturas_path, notice: "Miniatura was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_miniatura
      @miniatura = Miniatura.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def miniatura_params
      params.expect(miniatura: [ :descricao, :colecao, :linha, :marca_carro, :marca_mini, :ano ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = (column == params[:sort] && params[:direction] == "asc") ? "desc" : "asc"

    icon = if column == params[:sort]
      params[:direction] == "asc" ? "↑" : "↓"
    else
      ""
    end

    link_to "#{title} #{icon}".html_safe,
      { sort: column, direction: direction },
      class: "text-blue-600 hover:underline font-medium"
  end
end

app/helpers/miniaturas_helper.rb
module MiniaturasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Hot Wheels" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100">
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/miniaturas/_form.html.erb
<%= form_with(model: miniatura, class: "contents") do |form| %>
  <% if miniatura.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(miniatura.errors.count, "error") %> prohibited this miniatura from being saved:</h2>

      <ul class="list-disc ml-6">
        <% miniatura.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :descricao %>
    <%= form.text_field :descricao, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": miniatura.errors[:descricao].none?, "border-red-400 focus:outline-red-600": miniatura.errors[:descricao].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :colecao %>
    <%= form.text_field :colecao, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": miniatura.errors[:colecao].none?, "border-red-400 focus:outline-red-600": miniatura.errors[:colecao].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :linha %>
    <%= form.text_field :linha, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": miniatura.errors[:linha].none?, "border-red-400 focus:outline-red-600": miniatura.errors[:linha].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :marca_carro %>
    <%= form.text_field :marca_carro, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": miniatura.errors[:marca_carro].none?, "border-red-400 focus:outline-red-600": miniatura.errors[:marca_carro].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :marca_mini %>
    <%= form.text_field :marca_mini, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": miniatura.errors[:marca_mini].none?, "border-red-400 focus:outline-red-600": miniatura.errors[:marca_mini].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :ano %>
    <%= form.text_field :ano, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": miniatura.errors[:ano].none?, "border-red-400 focus:outline-red-600": miniatura.errors[:ano].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/miniaturas/_miniatura.html.erb
 <div id="<%= dom_id miniatura %>" class="sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Descricao:</strong>
    <strong> <%= miniatura.descricao %> </strong>
  </div>
  <div>
    <strong class="block font-medium mb-1">Colecao:</strong>
    <%= miniatura.colecao %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Linha:</strong>
    <%= miniatura.linha %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Marca carro:</strong>
    <%= miniatura.marca_carro %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Marca mini:</strong>
    <%= miniatura.marca_mini %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Ano:</strong>
    <%= miniatura.ano %>
  </div>
</div> 



  

app/views/miniaturas/edit.html.erb
<% content_for :title, "Editing miniatura" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing miniatura</h1>

  <%= render "form", miniatura: @miniatura %>

  <%= link_to "Show this miniatura", @miniatura, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to miniaturas", miniaturas_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/miniaturas/index.html.erb
<% content_for :title, "Miniaturas" %>

<div class="w-full">
    <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div class="flex justify-between items-center mb-8">
        <h1 class="font-bold text-4xl">Miniaturas</h1>
        <%= link_to "New miniatura", new_miniatura_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
    </div>

    <!-- FILTRO -->
    <div class="mb-6">
        <%= form_with url: miniaturas_path, method: :get, class: "flex gap-6 items-end" do |f| %>
        <div class="flex-1 max-w-xs">
            <%= f.label :marca_carro, "Filtrar por marca:", class: "block text-sm font-medium text-gray-700 mb-1" %>
            <%= f.select :marca_carro, 
          options_for_select(@marcas_carro, params[:marca_carro]), 
          { include_blank: "Todas as marcas" },
          class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 h-8" %>
        </div>

        <div class="flex gap-2">
            <%= f.submit "Filtrar", class: "px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition" %>

            <% if params[:marca_carro].present? %>
            <%= link_to "Limpar", miniaturas_path, class: "px-4 py-2 bg-gray-200 text-gray-700 rounded-md hover:bg-gray-300 transition" %>
            <% end %>
        </div>
        <% end %>
    </div>


        <!-- CONTADOR DE MINIS -->
    <div class="mb-4 text-md text-gray-600">
        Mostrando <span class="text-lg font-bold"><%= @miniaturas.count%></span>
        <%= @miniaturas.count == 1 ? "miniatura" : "miniaturas" %>
        <% if params[:marca_carro].present? %>
        da marca <strong class="uppercase"><%= params[:marca_carro] %></strong>
        <% end %>
        </div>

    <div id="miniaturas" class="min-w-full divide-y divide-gray-200 space-y-5 mb-6">
        <% if @miniaturas.any? %>
        <table id="miniaturas_table" class="min-w-full bg-gray-100 shadow-lg rounded-lg overflow-hidden uppercase">
            <thead>
                <tr class="bg-gray-200 text-left text-gray-600 font-semibold">
                    <th class="py-3 px-4">Descricao</th>
                    <th class="py-3 px-4">Colecao</th>
                    <th class="py-3 px-4"> <%= sortable "linha", "Linha" %></th>
                    <th class="py-3 px-4"> <%= sortable "marca_carro", "Marca Carro" %></th>
                    <th class="py-3 px-4"><%= sortable "marca_mini", "Marca Mini" %></th>
                    <th class="py-3 px-4">Ano</th>
                </tr>
            </thead>
            <tbody>
                <% @miniaturas.each do |miniatura| %>
                <tr class="hover:bg-gray-200 transition cursor-pointer" onclick="window.location='<%= miniatura_path(miniatura) %>'">
                    <td class="py-2 px-4"><%= miniatura.descricao %></td>
                    <td class="py-2 px-4"><%= miniatura.colecao %></td>
                    <td class="py-2 px-4"><%= miniatura.linha  %></td>
                    <td class="py-2 px-4"><%= miniatura.marca_carro %></td>
                    <td class="py-2 px-4"><%= miniatura.marca_mini %></td>
                    <td class="py-2 px-4"><%= miniatura.ano %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
        <% end %>
    </div>
</div>

app/views/miniaturas/new.html.erb
<% content_for :title, "New miniatura" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New miniatura</h1>

  <%= render "form", miniatura: @miniatura %>

  <%= link_to "Back to miniaturas", miniaturas_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/miniaturas/show.html.erb
<% content_for :title, "Showing miniatura" %>

<div class="md:w-2/3">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing miniatura</h1>

  <%= render @miniatura %>

  <%= link_to "Edit this miniatura", edit_miniatura_path(@miniatura), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to miniaturas", miniaturas_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this miniatura", @miniatura, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>